<?php
/**
 * Copyright 2026 Zwernemann
 * All Rights Reserved.
 */

namespace Zwernemann\MinResolver\Plugin\Framework\RequireJs;

use Magento\Framework\RequireJs\Config;

/**
 * Appends a robust safety wrapper to the requirejs-min-resolver.js output.
 *
 * Problem
 * -------
 * The original resolver (generated by Magento\Framework\RequireJs\Config::getMinResolverCode())
 * captures `baseUrl` once in a closure at script evaluation time. If RequireJS updates its
 * baseUrl later (require.config() call), the captured value is stale and the condition
 *   url.indexOf(baseUrl) === 0
 * fails → modules load without the .min suffix → 404 errors (e.g. mage/adminhtml/globals.js).
 *
 * Additionally, in the Magento Admin panel, AJAX-based page navigation can cause the script
 * to be re-injected and re-evaluated multiple times. Each evaluation wraps nameToUrl again
 * ("double-wrapping"), leading to incorrect URL resolution or infinite recursion in the
 * closure chain.
 *
 * Fix
 * ---
 * This plugin appends a second IIFE after the original resolver that:
 *   1. Uses an idempotency guard (__mRF flag) so re-execution has no effect.
 *   2. Reads ctx.config.baseUrl dynamically at call time (not captured in closure).
 *   3. Hooks require.s.newContext so future RequireJS contexts also get the resolver,
 *      except the '$' unbundled context used by mage/requirejs/mixins.js (which must
 *      return non-min paths for mixin lookups).
 *
 * Confirmed related Magento issues
 * ---------------------------------
 * - #38829  https://github.com/magento/magento2/issues/38829
 * - #38117  https://github.com/magento/magento2/issues/38117
 * - #28116  https://github.com/magento/magento2/issues/28116
 * - #4961   https://github.com/magento/magento2/issues/4961
 *
 * Scope
 * -----
 * Registered in global di.xml (covers both adminhtml and frontend areas).
 * The fix is harmless on the frontend; it is critical for admin AJAX navigation.
 */
class MinResolverPlugin
{
    /**
     * @param Config $subject
     * @param string $result
     * @return string
     */
    public function afterGetMinResolverCode(Config $subject, $result)
    {
        if (empty($result)) {
            return $result;
        }

        // Appended after the original resolver. Two IIFEs in sequence is valid JS.
        // Uses __mRF flag to be idempotent (safe if script is re-executed on AJAX nav).
        $extra = '(function(){' .
            'var a=function(c){' .
                'if(c.__mRF)return;' .
                'c.__mRF=true;' .
                'var p=c.nameToUrl;' .
                'c.nameToUrl=function(){' .
                    'var u=p.apply(c,arguments),b=c.config.baseUrl;' .
                    'if(u.indexOf(b)===0&&!/\\.min\\.js$/.test(u)){' .
                        'u=u.replace(/\\.js$/,\'.min.js\');' .
                    '}' .
                    'return u;' .
                '};' .
            '};' .
            'a(require.s.contexts._);' .
            'var n=require.s.newContext;' .
            'require.s.newContext=function(x){' .
                'var c=n.apply(this,arguments);' .
                'if(x!==\'$\'){a(c);}' .
                'return c;' .
            '};' .
        '})();';

        return $result . "\n" . $extra;
    }
}
